name: PR Validation

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Check code formatting
      run: ./gradlew check
      continue-on-error: true
      
    - name: Build mod
      run: ./gradlew build
      
    - name: Comment PR with build status
      if: always()
      uses: actions/github-script@v8
      with:
        script: |
          const status = '${{ job.status }}';
          const message = status === 'success' 
            ? '✅ Build succeeded! The mod compiled successfully.'
            : '❌ Build failed. Please check the logs for details.';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });
